### ISSUE TITLE
Minor observation of comment

### ISSUE THREAD

**Issue by Luv2C0d3** [RandyAbernethy/ThriftBook#14]
Randy, these next few lines will work without `sudo` in Linux only in cases where the user is member of the docker group. In windows powershell it is of course the way but in WSL2, I think you still need `sudo` .

https://github.com/RandyAbernethy/ThriftBook/blob/f1686f167b02b1ed4df4525898883ae1cc6890f3/Dockerfile#L3-L8

Pierre

**Comment by RandyAbernethy** [comment]
Indeed, I'll add a note. Thanks for the comment!
