### ISSUE TITLE
The book's release is canceled?

### ISSUE THREAD

**Issue by van2048** [RandyAbernethy/ThriftBook#7]
Hi! I got email:

> Not all manuscripts make it to the finish line to become published books. We regret to announce that an Early Access title you own, Programmer's Guide to Apache Thrift, will not be published. The content you've downloaded thus far is yours to keep, but there will be no further updates.

The book's release is canceled? The book was cool! What happened?

**Comment by RandyAbernethy** [comment]
Hey,
Checking with the publisher on this, would like to see it published (all the chapters are done!). Will come back.
--Randy

**Comment by RandyAbernethy** [comment]
Appears the book will be released and in short order!

**Comment by onriv** [comment]
https://www.manning.com/books/programmers-guide-to-apache-thrift-cx

Is the book still canceled? It says "We regret that Manning Publications will not be publishing this title.
" on the manning page

**Comment by RandyAbernethy** [comment]
No I think it should be released pretty soon. Waiting for the forward to
come back presently. Will ping Manning to see about updating the web.

**Comment by RandyAbernethy** [comment]
The book is out!
